export type RegistrationApprovalStatus = "pending" | "approved" | "rejected";
export type RegistrationMode = "team" | "individual";

export type SportsRegistration = {
  id: string;
  userKey: string | null;
  userName?: string;
  userEmail?: string;
  userPhone?: string;
  eventId: string;
  eventName: string;
  sportType: string;
  eventDate: string;
  eventVenue: string;
  submittedAt: string;
  registeredAt: string;
  fullName: string;
  email: string;
  phone: string;
  teamName: string;
  playerCount: number;
  specialRequirements?: string;
  registrationMode: RegistrationMode;
  approvalStatus: RegistrationApprovalStatus;
};

const REGISTRATIONS_STORAGE_KEY = "sports_registrations";

const demoRegistrations: SportsRegistration[] = [
  {
    id: "demo-registration-1",
    userKey: "email:adithi@sports.com",
    userName: "Adithi",
    userEmail: "adithi@sports.com",
    userPhone: "9876501234",
    eventId: "registration-demo-basketball",
    eventName: "Summer Hoops Invitational",
    sportType: "Basketball",
    eventDate: "2026-06-12T10:30:00.000Z",
    eventVenue: "Downtown Indoor Court",
    submittedAt: "2026-04-10T10:00:00.000Z",
    registeredAt: "2026-04-10T10:00:00.000Z",
    fullName: "Adithi",
    email: "adithi@sports.com",
    phone: "9876501234",
    teamName: "Skyline Hoopers",
    playerCount: 10,
    specialRequirements: "",
    registrationMode: "team",
    approvalStatus: "approved",
  },
  {
    id: "demo-registration-2",
    userKey: "email:akshitha@sports.com",
    userName: "Akshitha",
    userEmail: "akshitha@sports.com",
    userPhone: "9876505678",
    eventId: "registration-demo-cricket",
    eventName: "Premier Cricket Knockout",
    sportType: "Cricket",
    eventDate: "2026-06-18T05:00:00.000Z",
    eventVenue: "Lakeside Cricket Ground",
    submittedAt: "2026-04-11T08:15:00.000Z",
    registeredAt: "2026-04-11T08:15:00.000Z",
    fullName: "Akshitha",
    email: "akshitha@sports.com",
    phone: "9876505678",
    teamName: "Powerplay XI",
    playerCount: 13,
    specialRequirements: "Need warm-up nets access",
    registrationMode: "team",
    approvalStatus: "pending",
  },
  {
    id: "demo-registration-3",
    userKey: "email:riya@example.com",
    userName: "Riya Kapoor",
    userEmail: "riya@example.com",
    userPhone: "9898989898",
    eventId: "registration-demo-tennis",
    eventName: "Open Court Tennis Cup",
    sportType: "Tennis",
    eventDate: "2026-06-22T08:00:00.000Z",
    eventVenue: "Green Court Club",
    submittedAt: "2026-04-12T09:30:00.000Z",
    registeredAt: "2026-04-12T09:30:00.000Z",
    fullName: "Riya Kapoor",
    email: "riya@example.com",
    phone: "9898989898",
    teamName: "Individual Entry",
    playerCount: 1,
    specialRequirements: "",
    registrationMode: "individual",
    approvalStatus: "approved",
  },
  {
    id: "demo-registration-4",
    userKey: "email:naina@example.com",
    userName: "Naina Verma",
    userEmail: "naina@example.com",
    userPhone: "9765432101",
    eventId: "demo-event-5",
    eventName: "Aquatic Relay Clash",
    sportType: "Swimming",
    eventDate: "2026-05-20T07:00:00.000Z",
    eventVenue: "Blue Lane Aquatic Center",
    submittedAt: "2026-04-12T13:45:00.000Z",
    registeredAt: "2026-04-12T13:45:00.000Z",
    fullName: "Naina Verma",
    email: "naina@example.com",
    phone: "9765432101",
    teamName: "Individual Entry",
    playerCount: 1,
    specialRequirements: "Lane preference if possible",
    registrationMode: "individual",
    approvalStatus: "pending",
  },
  {
    id: "demo-registration-5",
    userKey: "email:aarav@example.com",
    userName: "Aarav Sharma",
    userEmail: "aarav@example.com",
    userPhone: "9988776655",
    eventId: "demo-event-1",
    eventName: "Football City Knockout",
    sportType: "Football",
    eventDate: "2026-05-04T09:00:00.000Z",
    eventVenue: "Central Turf Arena",
    submittedAt: "2026-04-13T11:00:00.000Z",
    registeredAt: "2026-04-13T11:00:00.000Z",
    fullName: "Aarav Sharma",
    email: "aarav@example.com",
    phone: "9988776655",
    teamName: "City Strikers",
    playerCount: 16,
    specialRequirements: "",
    registrationMode: "team",
    approvalStatus: "approved",
  },
  {
    id: "demo-registration-6",
    userKey: "email:aisha@example.com",
    userName: "Aisha Khan",
    userEmail: "aisha@example.com",
    userPhone: "9876512345",
    eventId: "demo-event-6",
    eventName: "Athletics Relay Knockout",
    sportType: "Athletics",
    eventDate: "2026-05-24T06:30:00.000Z",
    eventVenue: "National Track Field",
    submittedAt: "2026-04-13T15:20:00.000Z",
    registeredAt: "2026-04-13T15:20:00.000Z",
    fullName: "Aisha Khan",
    email: "aisha@example.com",
    phone: "9876512345",
    teamName: "Individual Entry",
    playerCount: 1,
    specialRequirements: "",
    registrationMode: "individual",
    approvalStatus: "rejected",
  },
  {
    id: "demo-registration-7",
    userKey: "email:meera@example.com",
    userName: "Meera Joshi",
    userEmail: "meera@example.com",
    userPhone: "9811112233",
    eventId: "demo-event-2",
    eventName: "Hoops Spring Challenge",
    sportType: "Basketball",
    eventDate: "2026-05-08T10:30:00.000Z",
    eventVenue: "Downtown Indoor Court",
    submittedAt: "2026-04-14T10:10:00.000Z",
    registeredAt: "2026-04-14T10:10:00.000Z",
    fullName: "Meera Joshi",
    email: "meera@example.com",
    phone: "9811112233",
    teamName: "Downtown Dunkers",
    playerCount: 9,
    specialRequirements: "",
    registrationMode: "team",
    approvalStatus: "approved",
  },
  {
    id: "demo-registration-8",
    userKey: "email:karan@example.com",
    userName: "Karan Malhotra",
    userEmail: "karan@example.com",
    userPhone: "9822223344",
    eventId: "demo-event-3",
    eventName: "Cricket Premier Cup",
    sportType: "Cricket",
    eventDate: "2026-05-12T04:30:00.000Z",
    eventVenue: "Lakeside Cricket Ground",
    submittedAt: "2026-04-14T11:30:00.000Z",
    registeredAt: "2026-04-14T11:30:00.000Z",
    fullName: "Karan Malhotra",
    email: "karan@example.com",
    phone: "9822223344",
    teamName: "Royal Batsmen",
    playerCount: 14,
    specialRequirements: "",
    registrationMode: "team",
    approvalStatus: "approved",
  },
  {
    id: "demo-registration-9",
    userKey: "email:ishita@example.com",
    userName: "Ishita Sen",
    userEmail: "ishita@example.com",
    userPhone: "9833334455",
    eventId: "demo-event-4",
    eventName: "Tennis Ladder Open",
    sportType: "Tennis",
    eventDate: "2026-05-16T08:00:00.000Z",
    eventVenue: "Green Court Club",
    submittedAt: "2026-04-14T12:20:00.000Z",
    registeredAt: "2026-04-14T12:20:00.000Z",
    fullName: "Ishita Sen",
    email: "ishita@example.com",
    phone: "9833334455",
    teamName: "Individual Entry",
    playerCount: 1,
    specialRequirements: "",
    registrationMode: "individual",
    approvalStatus: "pending",
  },
  {
    id: "demo-registration-10",
    userKey: "email:rohan@example.com",
    userName: "Rohan Patel",
    userEmail: "rohan@example.com",
    userPhone: "9844445566",
    eventId: "demo-event-1",
    eventName: "Football City Knockout",
    sportType: "Football",
    eventDate: "2026-05-04T09:00:00.000Z",
    eventVenue: "Central Turf Arena",
    submittedAt: "2026-04-14T14:40:00.000Z",
    registeredAt: "2026-04-14T14:40:00.000Z",
    fullName: "Rohan Patel",
    email: "rohan@example.com",
    phone: "9844445566",
    teamName: "Metro United",
    playerCount: 15,
    specialRequirements: "Need corner warm-up zone",
    registrationMode: "team",
    approvalStatus: "pending",
  },
  {
    id: "demo-registration-11",
    userKey: "email:sanya@example.com",
    userName: "Sanya Nair",
    userEmail: "sanya@example.com",
    userPhone: "9855556677",
    eventId: "demo-event-5",
    eventName: "Aquatic Relay Clash",
    sportType: "Swimming",
    eventDate: "2026-05-20T07:00:00.000Z",
    eventVenue: "Blue Lane Aquatic Center",
    submittedAt: "2026-04-15T08:00:00.000Z",
    registeredAt: "2026-04-15T08:00:00.000Z",
    fullName: "Sanya Nair",
    email: "sanya@example.com",
    phone: "9855556677",
    teamName: "Individual Entry",
    playerCount: 1,
    specialRequirements: "",
    registrationMode: "individual",
    approvalStatus: "approved",
  },
  {
    id: "demo-registration-12",
    userKey: "email:dev@example.com",
    userName: "Dev Raj",
    userEmail: "dev@example.com",
    userPhone: "9866667788",
    eventId: "demo-event-6",
    eventName: "Athletics Relay Knockout",
    sportType: "Athletics",
    eventDate: "2026-05-24T06:30:00.000Z",
    eventVenue: "National Track Field",
    submittedAt: "2026-04-15T09:10:00.000Z",
    registeredAt: "2026-04-15T09:10:00.000Z",
    fullName: "Dev Raj",
    email: "dev@example.com",
    phone: "9866667788",
    teamName: "Individual Entry",
    playerCount: 1,
    specialRequirements: "",
    registrationMode: "individual",
    approvalStatus: "approved",
  },
  {
    id: "demo-registration-13",
    userKey: "email:pooja@example.com",
    userName: "Pooja Iyer",
    userEmail: "pooja@example.com",
    userPhone: "9877778899",
    eventId: "registration-demo-football",
    eventName: "Metro Football Championship",
    sportType: "Football",
    eventDate: "2026-06-06T09:00:00.000Z",
    eventVenue: "Central Turf Arena",
    submittedAt: "2026-04-15T10:15:00.000Z",
    registeredAt: "2026-04-15T10:15:00.000Z",
    fullName: "Pooja Iyer",
    email: "pooja@example.com",
    phone: "9877778899",
    teamName: "East End Rovers",
    playerCount: 16,
    specialRequirements: "",
    registrationMode: "team",
    approvalStatus: "approved",
  },
  {
    id: "demo-registration-14",
    userKey: "email:vikram@example.com",
    userName: "Vikram Sethi",
    userEmail: "vikram@example.com",
    userPhone: "9888889900",
    eventId: "registration-demo-tennis",
    eventName: "Open Court Tennis Cup",
    sportType: "Tennis",
    eventDate: "2026-06-22T08:00:00.000Z",
    eventVenue: "Green Court Club",
    submittedAt: "2026-04-15T11:25:00.000Z",
    registeredAt: "2026-04-15T11:25:00.000Z",
    fullName: "Vikram Sethi",
    email: "vikram@example.com",
    phone: "9888889900",
    teamName: "Individual Entry",
    playerCount: 1,
    specialRequirements: "Need early slot",
    registrationMode: "individual",
    approvalStatus: "approved",
  },
  {
    id: "demo-registration-15",
    userKey: "email:neha@example.com",
    userName: "Neha Kulkarni",
    userEmail: "neha@example.com",
    userPhone: "9899990011",
    eventId: "registration-demo-cricket",
    eventName: "Premier Cricket Knockout",
    sportType: "Cricket",
    eventDate: "2026-06-18T05:00:00.000Z",
    eventVenue: "Lakeside Cricket Ground",
    submittedAt: "2026-04-15T13:05:00.000Z",
    registeredAt: "2026-04-15T13:05:00.000Z",
    fullName: "Neha Kulkarni",
    email: "neha@example.com",
    phone: "9899990011",
    teamName: "Spin Masters",
    playerCount: 12,
    specialRequirements: "",
    registrationMode: "team",
    approvalStatus: "pending",
  },
  {
    id: "demo-registration-16",
    userKey: "email:rahul@example.com",
    userName: "Rahul Bansal",
    userEmail: "rahul@example.com",
    userPhone: "9900001122",
    eventId: "demo-event-2",
    eventName: "Hoops Spring Challenge",
    sportType: "Basketball",
    eventDate: "2026-05-08T10:30:00.000Z",
    eventVenue: "Downtown Indoor Court",
    submittedAt: "2026-04-15T14:15:00.000Z",
    registeredAt: "2026-04-15T14:15:00.000Z",
    fullName: "Rahul Bansal",
    email: "rahul@example.com",
    phone: "9900001122",
    teamName: "Court Kings",
    playerCount: 8,
    specialRequirements: "",
    registrationMode: "team",
    approvalStatus: "rejected",
  },
  {
    id: "demo-registration-17",
    userKey: "email:tara@example.com",
    userName: "Tara Menon",
    userEmail: "tara@example.com",
    userPhone: "9911112233",
    eventId: "demo-event-5",
    eventName: "Aquatic Relay Clash",
    sportType: "Swimming",
    eventDate: "2026-05-20T07:00:00.000Z",
    eventVenue: "Blue Lane Aquatic Center",
    submittedAt: "2026-04-15T15:30:00.000Z",
    registeredAt: "2026-04-15T15:30:00.000Z",
    fullName: "Tara Menon",
    email: "tara@example.com",
    phone: "9911112233",
    teamName: "Individual Entry",
    playerCount: 1,
    specialRequirements: "",
    registrationMode: "individual",
    approvalStatus: "approved",
  },
  {
    id: "demo-registration-18",
    userKey: "email:arjun@example.com",
    userName: "Arjun Das",
    userEmail: "arjun@example.com",
    userPhone: "9922223344",
    eventId: "demo-event-6",
    eventName: "Athletics Relay Knockout",
    sportType: "Athletics",
    eventDate: "2026-05-24T06:30:00.000Z",
    eventVenue: "National Track Field",
    submittedAt: "2026-04-15T16:45:00.000Z",
    registeredAt: "2026-04-15T16:45:00.000Z",
    fullName: "Arjun Das",
    email: "arjun@example.com",
    phone: "9922223344",
    teamName: "Individual Entry",
    playerCount: 1,
    specialRequirements: "",
    registrationMode: "individual",
    approvalStatus: "pending",
  },
];

export const readRegistrations = (): SportsRegistration[] => {
  try {
    const storedRegistrations = localStorage.getItem(REGISTRATIONS_STORAGE_KEY);
    if (!storedRegistrations) {
      localStorage.setItem(REGISTRATIONS_STORAGE_KEY, JSON.stringify(demoRegistrations));
      return demoRegistrations;
    }

    const parsedRegistrations = JSON.parse(storedRegistrations) as SportsRegistration[];
    if (parsedRegistrations.length === 0) {
      localStorage.setItem(REGISTRATIONS_STORAGE_KEY, JSON.stringify(demoRegistrations));
      return demoRegistrations;
    }

    const existingIds = new Set(parsedRegistrations.map((registration) => registration.id));
    const mergedRegistrations = [...parsedRegistrations, ...demoRegistrations.filter((registration) => !existingIds.has(registration.id))];
    if (mergedRegistrations.length !== parsedRegistrations.length) {
      localStorage.setItem(REGISTRATIONS_STORAGE_KEY, JSON.stringify(mergedRegistrations));
    }

    return mergedRegistrations;
  } catch {
    return demoRegistrations;
  }
};

export const writeRegistrations = (registrations: SportsRegistration[]) => {
  localStorage.setItem(REGISTRATIONS_STORAGE_KEY, JSON.stringify(registrations));
};
