// Generated by tools/export_ecommerce_products.py.
// Source: /Users/ananyagyana/Desktop/Sports_and_Outdoors_5.json
// The source contains reviews and ASINs; display metadata is deterministically derived.

export const ecommerceProducts = [
  {
    "id": "B000GCRWCG",
    "sportId": "badminton",
    "name": "Decathlon Badminton Gear Accessory RWCG",
    "category": "accessories",
    "price": 3558,
    "brand": "Decathlon",
    "rating": 4.7,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 393 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:393"
    ]
  },
  {
    "id": "B004U8CP88",
    "sportId": "cycling",
    "name": "Adidas Cycling Gear Accessory CP88",
    "category": "accessories",
    "price": 4403,
    "brand": "Adidas",
    "rating": 4.6,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 357 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:357"
    ]
  },
  {
    "id": "B001949TKS",
    "sportId": "cycling",
    "name": "Wilson Cycling Gear Accessory 9TKS",
    "category": "accessories",
    "price": 4517,
    "brand": "Wilson",
    "rating": 4.5,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 298 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:298"
    ]
  },
  {
    "id": "B0009R96YK",
    "sportId": "cycling",
    "name": "Yonex Cycling Gear Accessory 96YK",
    "category": "accessories",
    "price": 2469,
    "brand": "Yonex",
    "rating": 4.6,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 288 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:288"
    ]
  },
  {
    "id": "B0018S4XIS",
    "sportId": "gym",
    "name": "Wilson Gym Gear Accessory 4XIS",
    "category": "accessories",
    "price": 3168,
    "brand": "Wilson",
    "rating": 4.7,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 282 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:282"
    ]
  },
  {
    "id": "B000AO5L8W",
    "sportId": "cycling",
    "name": "Nivia Cycling Gear Accessory 5L8W",
    "category": "accessories",
    "price": 2242,
    "brand": "Nivia",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 279 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:279"
    ]
  },
  {
    "id": "B0026OOS60",
    "sportId": "gym",
    "name": "SG Gym Gear Accessory OS60",
    "category": "accessories",
    "price": 3396,
    "brand": "SG",
    "rating": 4.5,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 258 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:258"
    ]
  },
  {
    "id": "B00437VTJ2",
    "sportId": "cycling",
    "name": "SG Cycling Gear Accessory VTJ2",
    "category": "accessories",
    "price": 3948,
    "brand": "SG",
    "rating": 4.6,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 242 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:242"
    ]
  },
  {
    "id": "B001MK3GFS",
    "sportId": "cycling",
    "name": "Puma Cycling Performance Equipment 3GFS",
    "category": "equipment",
    "price": 7079,
    "brand": "Puma",
    "rating": 4.6,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 234 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:234"
    ]
  },
  {
    "id": "B000NLA4PM",
    "sportId": "swimming",
    "name": "Nivia Swimming Gear Accessory A4PM",
    "category": "accessories",
    "price": 2502,
    "brand": "Nivia",
    "rating": 4.7,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 233 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:233"
    ]
  },
  {
    "id": "B002TALNRS",
    "sportId": "cycling",
    "name": "Decathlon Cycling Gear Accessory LNRS",
    "category": "accessories",
    "price": 4176,
    "brand": "Decathlon",
    "rating": 4.7,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 224 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:224"
    ]
  },
  {
    "id": "B002KT3XQC",
    "sportId": "cycling",
    "name": "Wilson Cycling Training Apparel 3XQC",
    "category": "clothing",
    "price": 2759,
    "brand": "Wilson",
    "rating": 4.6,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 223 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:223"
    ]
  },
  {
    "id": "B000FI6XGC",
    "sportId": "cycling",
    "name": "Nivia Cycling Gear Accessory 6XGC",
    "category": "accessories",
    "price": 2469,
    "brand": "Nivia",
    "rating": 4.2,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 218 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:218"
    ]
  },
  {
    "id": "B000RYAKHC",
    "sportId": "cycling",
    "name": "Wilson Cycling Performance Equipment AKHC",
    "category": "equipment",
    "price": 6659,
    "brand": "Wilson",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 216 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:216"
    ]
  },
  {
    "id": "B0068VM5T4",
    "sportId": "gym",
    "name": "Nike Gym Training Apparel M5T4",
    "category": "clothing",
    "price": 2639,
    "brand": "Nike",
    "rating": 4.6,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 201 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:201"
    ]
  },
  {
    "id": "B00435IPFK",
    "sportId": "cycling",
    "name": "Cosco Cycling Gear Accessory IPFK",
    "category": "accessories",
    "price": 4385,
    "brand": "Cosco",
    "rating": 4.8,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 193 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:193"
    ]
  },
  {
    "id": "B000LIFB7S",
    "sportId": "cycling",
    "name": "Speedo Cycling Gear Accessory FB7S",
    "category": "accessories",
    "price": 2779,
    "brand": "Speedo",
    "rating": 4.0,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 188 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:188"
    ]
  },
  {
    "id": "B001LF3IB6",
    "sportId": "badminton",
    "name": "Yonex Badminton Gear Accessory 3IB6",
    "category": "accessories",
    "price": 3064,
    "brand": "Yonex",
    "rating": 4.7,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 185 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:185"
    ]
  },
  {
    "id": "B001ID4ZY0",
    "sportId": "gym",
    "name": "Yonex Gym Gear Accessory 4ZY0",
    "category": "accessories",
    "price": 1984,
    "brand": "Yonex",
    "rating": 4.1,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 182 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:182"
    ]
  },
  {
    "id": "B001TR7QZA",
    "sportId": "gym",
    "name": "Spartan Gym Gear Accessory 7QZA",
    "category": "accessories",
    "price": 4029,
    "brand": "Spartan",
    "rating": 4.1,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 181 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:181"
    ]
  },
  {
    "id": "B000FN7UWS",
    "sportId": "swimming",
    "name": "Wilson Swimming Gear Accessory 7UWS",
    "category": "accessories",
    "price": 2207,
    "brand": "Wilson",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 174 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:174"
    ]
  },
  {
    "id": "B000JF2ZB8",
    "sportId": "cycling",
    "name": "Spartan Cycling Gear Accessory 2ZB8",
    "category": "accessories",
    "price": 2389,
    "brand": "Spartan",
    "rating": 4.5,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 169 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:169"
    ]
  },
  {
    "id": "B000FIE3WI",
    "sportId": "cycling",
    "name": "Reebok Cycling Gear Accessory E3WI",
    "category": "accessories",
    "price": 4315,
    "brand": "Reebok",
    "rating": 4.7,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 166 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:166"
    ]
  },
  {
    "id": "B002Y1IO7E",
    "sportId": "cycling",
    "name": "Spartan Cycling Gear Accessory IO7E",
    "category": "accessories",
    "price": 2148,
    "brand": "Spartan",
    "rating": 4.1,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 164 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:164"
    ]
  },
  {
    "id": "B0000533G7",
    "sportId": "gym",
    "name": "Cosco Gym Gear Accessory 33G7",
    "category": "accessories",
    "price": 1932,
    "brand": "Cosco",
    "rating": 4.7,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 162 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:162"
    ]
  },
  {
    "id": "B007WQKT1K",
    "sportId": "gym",
    "name": "Reebok Gym Gear Accessory KT1K",
    "category": "accessories",
    "price": 3173,
    "brand": "Reebok",
    "rating": 3.8,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 158 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:158"
    ]
  },
  {
    "id": "B0026HYWRW",
    "sportId": "gym",
    "name": "SG Gym Gear Accessory YWRW",
    "category": "accessories",
    "price": 1689,
    "brand": "SG",
    "rating": 4.6,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 156 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:156"
    ]
  },
  {
    "id": "B000HX04TW",
    "sportId": "gym",
    "name": "SG Gym Gear Accessory 04TW",
    "category": "accessories",
    "price": 3953,
    "brand": "SG",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 152 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:152"
    ]
  },
  {
    "id": "B001LF3FQ4",
    "sportId": "gym",
    "name": "Wilson Gym Gear Accessory 3FQ4",
    "category": "accessories",
    "price": 3012,
    "brand": "Wilson",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 140 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:140"
    ]
  },
  {
    "id": "B002KW3HI8",
    "sportId": "cycling",
    "name": "Nike Cycling Training Apparel 3HI8",
    "category": "clothing",
    "price": 4098,
    "brand": "Nike",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 137 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:137"
    ]
  },
  {
    "id": "B000OR115W",
    "sportId": "gym",
    "name": "Adidas Gym Gear Accessory 115W",
    "category": "accessories",
    "price": 4025,
    "brand": "Adidas",
    "rating": 4.5,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 136 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:136"
    ]
  },
  {
    "id": "B00012M5MS",
    "sportId": "cycling",
    "name": "Yonex Cycling Performance Equipment M5MS",
    "category": "equipment",
    "price": 5072,
    "brand": "Yonex",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 132 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:132"
    ]
  },
  {
    "id": "B002MFK7H2",
    "sportId": "cycling",
    "name": "Decathlon Cycling Gear Accessory K7H2",
    "category": "accessories",
    "price": 3882,
    "brand": "Decathlon",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 131 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:131"
    ]
  },
  {
    "id": "B00FA2RLX2",
    "sportId": "gym",
    "name": "Cosco Gym Gear Accessory RLX2",
    "category": "accessories",
    "price": 4121,
    "brand": "Cosco",
    "rating": 4.9,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 129 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:129"
    ]
  },
  {
    "id": "B005DVA57Y",
    "sportId": "cycling",
    "name": "Nike Cycling Gear Accessory A57Y",
    "category": "accessories",
    "price": 4332,
    "brand": "Nike",
    "rating": 4.6,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 129 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:129"
    ]
  },
  {
    "id": "B000DZD3FQ",
    "sportId": "cycling",
    "name": "Speedo Cycling Gear Accessory D3FQ",
    "category": "accessories",
    "price": 1944,
    "brand": "Speedo",
    "rating": 4.2,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 129 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:129"
    ]
  },
  {
    "id": "B0034C6GDG",
    "sportId": "swimming",
    "name": "Puma Swimming Gear Accessory 6GDG",
    "category": "accessories",
    "price": 3000,
    "brand": "Puma",
    "rating": 4.1,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 129 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:129"
    ]
  },
  {
    "id": "B000BNS62A",
    "sportId": "cycling",
    "name": "Nivia Cycling Performance Equipment S62A",
    "category": "equipment",
    "price": 5263,
    "brand": "Nivia",
    "rating": 4.5,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 128 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:128"
    ]
  },
  {
    "id": "B000FI6YOS",
    "sportId": "cycling",
    "name": "Nike Cycling Gear Accessory 6YOS",
    "category": "accessories",
    "price": 3076,
    "brand": "Nike",
    "rating": 4.2,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 127 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:127"
    ]
  },
  {
    "id": "B001GUP8JG",
    "sportId": "gym",
    "name": "Wilson Gym Gear Accessory P8JG",
    "category": "accessories",
    "price": 3997,
    "brand": "Wilson",
    "rating": 4.6,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 125 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:125"
    ]
  },
  {
    "id": "B001C1UGVO",
    "sportId": "gym",
    "name": "Nike Gym Gear Accessory UGVO",
    "category": "accessories",
    "price": 1608,
    "brand": "Nike",
    "rating": 4.5,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 125 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:125"
    ]
  },
  {
    "id": "B001AZNATC",
    "sportId": "football",
    "name": "Cosco Football Gear Accessory NATC",
    "category": "accessories",
    "price": 1982,
    "brand": "Cosco",
    "rating": 4.3,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 125 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:125"
    ]
  },
  {
    "id": "B001YK4M18",
    "sportId": "swimming",
    "name": "SG Swimming Performance Equipment 4M18",
    "category": "equipment",
    "price": 5089,
    "brand": "SG",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 123 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:123"
    ]
  },
  {
    "id": "B000WY6ZXA",
    "sportId": "cycling",
    "name": "Decathlon Cycling Gear Accessory 6ZXA",
    "category": "accessories",
    "price": 4200,
    "brand": "Decathlon",
    "rating": 4.3,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 122 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:122"
    ]
  },
  {
    "id": "B00BGO0Q9O",
    "sportId": "gym",
    "name": "Speedo Gym Gear Accessory 0Q9O",
    "category": "accessories",
    "price": 4103,
    "brand": "Speedo",
    "rating": 3.6,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 122 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:122"
    ]
  },
  {
    "id": "B001DDPFYY",
    "sportId": "gym",
    "name": "Yonex Gym Gear Accessory PFYY",
    "category": "accessories",
    "price": 1476,
    "brand": "Yonex",
    "rating": 4.7,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 118 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:118"
    ]
  },
  {
    "id": "B00B1N0R6C",
    "sportId": "gym",
    "name": "Wilson Gym Performance Equipment 0R6C",
    "category": "equipment",
    "price": 3355,
    "brand": "Wilson",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 118 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:118"
    ]
  },
  {
    "id": "B000H87PUI",
    "sportId": "cycling",
    "name": "Adidas Cycling Training Apparel 7PUI",
    "category": "clothing",
    "price": 5144,
    "brand": "Adidas",
    "rating": 4.6,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 114 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:114"
    ]
  },
  {
    "id": "B005YPK8G2",
    "sportId": "cycling",
    "name": "Nike Cycling Gear Accessory K8G2",
    "category": "accessories",
    "price": 4180,
    "brand": "Nike",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 114 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:114"
    ]
  },
  {
    "id": "B000HJBKMQ",
    "sportId": "swimming",
    "name": "Yonex Swimming Gear Accessory BKMQ",
    "category": "accessories",
    "price": 3186,
    "brand": "Yonex",
    "rating": 4.5,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 113 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:113"
    ]
  },
  {
    "id": "B000EH0NLK",
    "sportId": "gym",
    "name": "Yonex Gym Gear Accessory 0NLK",
    "category": "accessories",
    "price": 1463,
    "brand": "Yonex",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 113 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:113"
    ]
  },
  {
    "id": "B00CWVP8PC",
    "sportId": "cycling",
    "name": "Adidas Cycling Training Apparel P8PC",
    "category": "clothing",
    "price": 3458,
    "brand": "Adidas",
    "rating": 4.0,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 112 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:112"
    ]
  },
  {
    "id": "B002LLPILC",
    "sportId": "gym",
    "name": "Nike Gym Gear Accessory PILC",
    "category": "accessories",
    "price": 3505,
    "brand": "Nike",
    "rating": 4.8,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 111 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:111"
    ]
  },
  {
    "id": "B001EJMS6K",
    "sportId": "gym",
    "name": "SG Gym Performance Equipment MS6K",
    "category": "equipment",
    "price": 5627,
    "brand": "SG",
    "rating": 4.3,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 110 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:110"
    ]
  },
  {
    "id": "B00074H6RO",
    "sportId": "gym",
    "name": "Decathlon Gym Performance Equipment H6RO",
    "category": "equipment",
    "price": 4577,
    "brand": "Decathlon",
    "rating": 4.3,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 110 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:110"
    ]
  },
  {
    "id": "B000P1RO7Q",
    "sportId": "cycling",
    "name": "Nivia Cycling Gear Accessory RO7Q",
    "category": "accessories",
    "price": 3595,
    "brand": "Nivia",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 108 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:108"
    ]
  },
  {
    "id": "B0007IS74G",
    "sportId": "gym",
    "name": "Adidas Gym Gear Accessory S74G",
    "category": "accessories",
    "price": 3381,
    "brand": "Adidas",
    "rating": 4.5,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 107 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:107"
    ]
  },
  {
    "id": "B000C17L2W",
    "sportId": "cycling",
    "name": "Puma Cycling Gear Accessory 7L2W",
    "category": "accessories",
    "price": 1886,
    "brand": "Puma",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 107 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:107"
    ]
  },
  {
    "id": "B006QQX3C4",
    "sportId": "cycling",
    "name": "Wilson Cycling Performance Equipment X3C4",
    "category": "equipment",
    "price": 4742,
    "brand": "Wilson",
    "rating": 4.1,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 107 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:107"
    ]
  },
  {
    "id": "B001ARYU58",
    "sportId": "gym",
    "name": "SG Gym Training Apparel YU58",
    "category": "clothing",
    "price": 2618,
    "brand": "SG",
    "rating": 4.7,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 106 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:106"
    ]
  },
  {
    "id": "7245456313",
    "sportId": "gym",
    "name": "Cosco Gym Gear Accessory 6313",
    "category": "accessories",
    "price": 3379,
    "brand": "Cosco",
    "rating": 4.5,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 106 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:106"
    ]
  },
  {
    "id": "B00142FFCG",
    "sportId": "cycling",
    "name": "Spartan Cycling Gear Accessory FFCG",
    "category": "accessories",
    "price": 3815,
    "brand": "Spartan",
    "rating": 4.6,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 105 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:105"
    ]
  },
  {
    "id": "B0089JOTJ2",
    "sportId": "cycling",
    "name": "SG Cycling Gear Accessory OTJ2",
    "category": "accessories",
    "price": 2905,
    "brand": "SG",
    "rating": 4.3,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 105 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:105"
    ]
  },
  {
    "id": "B00152R8Q6",
    "sportId": "cycling",
    "name": "SG Cycling Training Apparel R8Q6",
    "category": "clothing",
    "price": 3012,
    "brand": "SG",
    "rating": 4.1,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 104 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:104"
    ]
  },
  {
    "id": "B000KBEH1W",
    "sportId": "cycling",
    "name": "Adidas Cycling Gear Accessory EH1W",
    "category": "accessories",
    "price": 3241,
    "brand": "Adidas",
    "rating": 4.5,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 103 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:103"
    ]
  },
  {
    "id": "B00598KU7Q",
    "sportId": "swimming",
    "name": "Nike Swimming Gear Accessory KU7Q",
    "category": "accessories",
    "price": 3728,
    "brand": "Nike",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 103 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:103"
    ]
  },
  {
    "id": "B000TG8D6I",
    "sportId": "gym",
    "name": "Nike Gym Training Apparel 8D6I",
    "category": "clothing",
    "price": 4006,
    "brand": "Nike",
    "rating": 4.5,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 102 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:102"
    ]
  },
  {
    "id": "B008DNAJ5M",
    "sportId": "gym",
    "name": "Speedo Gym Performance Equipment AJ5M",
    "category": "equipment",
    "price": 5369,
    "brand": "Speedo",
    "rating": 4.8,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 100 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:100"
    ]
  },
  {
    "id": "B001AIBJNS",
    "sportId": "gym",
    "name": "Wilson Gym Gear Accessory BJNS",
    "category": "accessories",
    "price": 2794,
    "brand": "Wilson",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 100 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:100"
    ]
  },
  {
    "id": "B00165P4WC",
    "sportId": "cycling",
    "name": "SG Cycling Gear Accessory P4WC",
    "category": "accessories",
    "price": 3458,
    "brand": "SG",
    "rating": 4.5,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 99 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:99"
    ]
  },
  {
    "id": "B002OEQ50Y",
    "sportId": "gym",
    "name": "Puma Gym Gear Accessory Q50Y",
    "category": "accessories",
    "price": 3474,
    "brand": "Puma",
    "rating": 4.3,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 99 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:99"
    ]
  },
  {
    "id": "B000ACAMJC",
    "sportId": "cycling",
    "name": "Puma Cycling Gear Accessory AMJC",
    "category": "accessories",
    "price": 3228,
    "brand": "Puma",
    "rating": 4.5,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 98 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:98"
    ]
  },
  {
    "id": "B0012Q2S4W",
    "sportId": "swimming",
    "name": "SG Swimming Gear Accessory 2S4W",
    "category": "accessories",
    "price": 3488,
    "brand": "SG",
    "rating": 4.2,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 98 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:98"
    ]
  },
  {
    "id": "B004Y69QX8",
    "sportId": "cycling",
    "name": "SG Cycling Gear Accessory 9QX8",
    "category": "accessories",
    "price": 2657,
    "brand": "SG",
    "rating": 4.4,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 97 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:97"
    ]
  },
  {
    "id": "B002B7LTBY",
    "sportId": "cycling",
    "name": "Reebok Cycling Performance Equipment LTBY",
    "category": "equipment",
    "price": 5110,
    "brand": "Reebok",
    "rating": 4.6,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 96 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:96"
    ]
  },
  {
    "id": "B001ANQVYU",
    "sportId": "gym",
    "name": "Spartan Gym Training Apparel QVYU",
    "category": "clothing",
    "price": 3700,
    "brand": "Spartan",
    "rating": 4.7,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 94 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:94"
    ]
  },
  {
    "id": "B000HU11ZG",
    "sportId": "cycling",
    "name": "Reebok Cycling Gear Accessory 11ZG",
    "category": "accessories",
    "price": 3104,
    "brand": "Reebok",
    "rating": 4.2,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 94 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:94"
    ]
  },
  {
    "id": "B008RJMSLK",
    "sportId": "cycling",
    "name": "Spartan Cycling Gear Accessory MSLK",
    "category": "accessories",
    "price": 3218,
    "brand": "Spartan",
    "rating": 4.1,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 94 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:94"
    ]
  },
  {
    "id": "B008JXV2PM",
    "sportId": "gym",
    "name": "Adidas Gym Gear Accessory V2PM",
    "category": "accessories",
    "price": 3686,
    "brand": "Adidas",
    "rating": 4.8,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 93 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:93"
    ]
  },
  {
    "id": "B00022O5SO",
    "sportId": "football",
    "name": "Puma Football Gear Accessory O5SO",
    "category": "accessories",
    "price": 3377,
    "brand": "Puma",
    "rating": 4.5,
    "image": "",
    "description": "Amazon Sports and Outdoors item with 93 review interactions used for recommender training.",
    "tags": [
      "amazon-sports-outdoors",
      "reviews:93"
    ]
  }
] satisfies import("./sportsData").Product[];
